// organizer
export const ADD_TIMELINE = "ADD_TIMELINE";
export const DELETE_TIMELINE = "DELETE_TIMELINE";
export const ADD_TRIAL = "ADD_TRIAL";
export const DELETE_TRIAL = "DELETE_TRIAL";
export const MOVE_TO = "MOVE_TO";
export const MOVE_INTO = "MOVE_INTO";
export const MOVE_BY_KEYBOARD = "MOVE_BY_KEYBOARD";
export const ON_PREVIEW = "ON_PREVIEW";
export const ON_TOGGLE = "ON_TOGGLE";
export const SET_TOGGLE_COLLECTIVELY = "SET_TOGGLE_COLLECTIVELY";
export const SET_COLLAPSED = "SET_COLLAPSED";
export const INSERT_NODE_AFTER_TRIAL = "INSERT_NODE_AFTER_TRIAL";
export const DUPLICATE_TIMELINE = "DUPLICATE_TIMELINE";
export const DUPLICATE_TRIAL = "DUPLICATE_TRIAL";
export const SET_NAME = "SET_NAME";

// jsPsych init editor
export const SET_JSPSYCH_INIT = "SET_JSPSYCH_INIT";

// preview
export const PLAY_ALL = "PLAY_ALL";

// main
export const SET_EXPERIMENT_NAME = "SET_EXPERIMENT_NAME";

// editor
export const SET_PLUGIN_PARAMTER = "SET_PLUGIN_PARAMTER";
export const SET_PLUGIN_PARAMTER_MODE = "SET_PLUGIN_PARAMTER_MODE";
export const UPDATE_MEDIA = "UPDATE_MEDIA";

// editor - TrialForm Actions
export const CHANGE_PLUGIN_TYPE = "CHANGE_PLUGIN_TYPE";

// editor - TimelineForm Actions
export const UPDATE_TIMELINE_VARIABLE_TABLE_ROW = "UPDATE_TIMELINE_VARIABLE_TABLE_ROW";
export const UPDATE_TIMELINE_VARIABLE_TABLE_CELL = "UPDATE_TIMELINE_VARIABLE_TABLE_CELL";
export const UPDATE_TIMELINE_VARIABLE_TABLE_HEADER = "UPDATE_TIMELINE_VARIABLE_TABLE_HEADER";
export const ADD_TIMELINE_VARIABLE_ROW = "ADD_TIMELINE_VARIABLE_ROW";
export const ADD_TIMELINE_VARIABLE_COLUMN = "ADD_TIMELINE_VARIABLE_COLUMN";
export const DELETE_TIMELINE_VARIABLE_ROW = "DELETE_TIMELINE_VARIABLE_ROW";
export const DELETE_TIMELINE_VARIABLE_COLUMN = "DELETE_TIMELINE_VARIABLE_COLUMN";
export const SET_SAMPLING_METHOD = "SET_SAMPLING_METHOD";
export const SET_SAMPLE_SIZE = "SET_SAMPLE_SIZE";
export const SET_RANDOMIZE = "SET_RANDOMIZE";
export const SET_REPETITIONS = "SET_REPETITIONS";
export const SET_LOOP_FUNCTION = "SET_LOOP_FUNCTION";
export const SET_CONDITION_FUNCTION = "SET_CONDITION_FUNCTION";

// User Actions
export const SIGN_IN_OUT = "SIGN_IN_OUT";
export const SET_LOGIN_WINDOW = "SET_LOGIN_WINDOW";

// Backend Actions
export const SIGN_UP_PUSH = "SIGN_UP_PUSH";
export const SIGN_IN_PULL = "SIGN_IN_PULL";
export const CLICK_SAVE_PUSH = "CLICK_SAVE_PUSH";
export const PULL_EXPERIMENT = "PULL_EXPERIMENT";
export const DELETE_EXPERIMENT = "DELETE_EXPERIMENT";
export const NEW_EXPERIMENT = "NEW_EXPERIMENT";
export const SAVE_AS_PUSH = "SAVE_AS_PUSH";
export const DUPLICATE_EXPERIMENT = "DUPLICATE_EXPERIMENT";

// Notification Actions
export const NOTIFICATION = "NOTIFICATION";
export const NOTIFICATION_CLOSE = "NOTIFICATION_CLOSE";